## DEV

#spring.application.name=java-algorithms-api
#server.port=8089
#debug=false
#
## Actuator
#management.endpoints.web.exposure.include=health,info,metrics,prometheus
#management.endpoint.health.show-details=always
#
## Informacion visible en /actuator/info
#info.app.name=Java Algorithms API
#info.app.version=1.0.0
#info.app.author=Efren David